Fix warning
The warning:
```
warning: incompatible types given as default arguments to write_processor_marker/1:

         empty_map()

     but expected one of:

         %{..., __struct__: not_set(), cache_location: term(), cache_record_id: term()}

     type warning found at:
     │
 237 │   def write_processor_marker(attrs \\ %{}) do
     │                                    ~
     │
     └─ lib/dpul_collections/indexing_pipeline.ex:237:36: DpulCollections.IndexingPipeline.write_processor_marker/0

```

This is saying "your function requires these properties, but your
default doesn't have them - if you don't pass something to this function
it'll just break, what are you doing??"